### ISSUE TITLE
Investigate Yosys `$concat` semantics

### ISSUE THREAD

**Issue by ninehusky** [uwsampl/churchroad#48]
According to [this](https://www.reddit.com/r/yosys/comments/4e9co6/very_basic_question_about_cellmapping/) post, the semantics for a Yosys `$concat` cell is `Y = { B, A }`. Let's confirm that this is correct, as #47 assumes this is the case.

**Comment by gussmith23** [comment]
Closing this -- a post on Reddit is fine enough confirmation for now. This issue is now in our issue history, so if problems with concat come up later, people should be able to end up here and make some sense of things.
